Repository neo4j/cypher-shell, pull requests merged in 2019-12, with the labels that each got.

#181 Change formatting ResultTables with long values
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TableOutputFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TableOutputFormatterTest.java
Labels: 1.1, bug

#185 Change query to execute against system to ping for version
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.0, bug

#184 Change formatting ResultTables with long values
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TableOutputFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TableOutputFormatterTest.java
Labels: 4.1, bug, cherry-picked

#186 Change query to execute against system to ping for version
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.1, bug

#183 Change formatting ResultTables with long values
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TableOutputFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TableOutputFormatterTest.java
Labels: 4.0, bug, cherry-picked

#182 Fix connection when default database is unavailable
  build.gradle
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/InteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/log/AnsiLogger.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/OfflineTestShell.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/InteractiveShellRunnerTest.java
  cypher-shell/src/test/java/org/neo4j/shell/test/bolt/FakeDriver.java
Labels: 4.0, bug

#187 Update the driver version to 4.0
  build.gradle
Labels: 4.0

#189 Fix connection when default database is unavailable
  build.gradle
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/InteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/log/AnsiLogger.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/OfflineTestShell.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/InteractiveShellRunnerTest.java
  cypher-shell/src/test/java/org/neo4j/shell/test/bolt/FakeDriver.java
Labels: 4.1, bug, cherry-picked

#190 Update the driver version to 4.0
  build.gradle
Labels: 4.1
