Repository neo4j/cypher-shell, pull requests merged in 2020-10, with the labels that each got.

#256 Support host:port without scheme
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
Labels: 4.1, bug, cherry-picked

#254 Support host:port without scheme
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgs.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
Labels: 4.0, bug

#257 Support host:port without scheme
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
Labels: 4.2, bug, cherry-picked

#259 Update to driver version 4.2.0-alpha01
  build.gradle
Labels: 4.2, changelog

#258 Update to driver version 1.7.5
  build.gradle
Labels: 1.1, changelog

#251 Use JavaCC for parameter parsing
  build.gradle
  cypher-shell/build.gradle
  cypher-shell/src/main/java/org/neo4j/shell/Connector.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/Main.java
  cypher-shell/src/main/java/org/neo4j/shell/ParameterMap.java
  cypher-shell/src/main/java/org/neo4j/shell/ShellParameterMap.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/AddParamArgumentAction.java
  cypher-shell/src/main/java/org/neo4j/shell/commands/Param.java
  cypher-shell/src/main/java/org/neo4j/shell/exception/ParameterException.java
  cypher-shell/src/main/java/org/neo4j/shell/exception/ThrowingAction.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/util/ParameterSetter.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
  cypher-shell/src/test/java/org/neo4j/shell/ShellParameterMapTest.java
  cypher-shell/src/test/java/org/neo4j/shell/commands/ParamTest.java
Labels: 4.2

#262 Nicer formatting for Duration
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/OutputFormatter.java
Labels: 4.2, bug

#269 Nicer formatting for Duration
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/OutputFormatter.java
Labels: cherry-picked

#270 Nicer formatting for Duration
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/OutputFormatter.java
Labels: 4.0, cherry-picked

#271 Update version
  cypher-shell/src/test/java/org/neo4j/shell/state/BoltStateHandlerTest.java
Labels: 4.2
