Repository neo4j/cypher-shell, pull requests merged in 2020-11, with the labels that each got.

#280 Ignore empty statements
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellPlainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 4.2, cherry-picked

#281 Ignore empty statements.
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellPlainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 4.1, cherry-picked

#282 Ignore empty statements.
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 4.0, cherry-picked

#283 Ignore empty statements.
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 1.1, cherry-picked

#284 update driver
  build.gradle
Labels: 4.2
