Repository neo4j/cypher-shell, pull requests merged in 2020-02, with the labels that each got.

#202 Allow user to update expired password non-interactively
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/ConnectionConfig.java
  cypher-shell/src/main/java/org/neo4j/shell/Connector.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/Main.java
  cypher-shell/src/main/java/org/neo4j/shell/ShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/InteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/NonInteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/StringShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/commands/Exit.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
  cypher-shell/src/test/java/org/neo4j/shell/MainTest.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/StringShellRunnerTest.java
Labels: 4.0, bug, changelog

#206 Show memory in Profile.
  build.gradle
  cypher-shell/build.gradle
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellPlainIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/OutputFormatter.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TablePlanFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/PrettyPrinterTest.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TableOutputFormatterTest.java
Labels: 4.1, changelog

#204 Automatically fall back to bolt protocol
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellProtocolIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/state/BoltStateHandlerTest.java
Labels: 4.0, cherry-picked

#207 4.1 allow password change
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/ConnectionConfig.java
  cypher-shell/src/main/java/org/neo4j/shell/Connector.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/Main.java
  cypher-shell/src/main/java/org/neo4j/shell/ShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/InteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/NonInteractiveShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/StringShellRunner.java
  cypher-shell/src/main/java/org/neo4j/shell/commands/Exit.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
  cypher-shell/src/test/java/org/neo4j/shell/MainTest.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/StringShellRunnerTest.java
Labels: 4.1, bug, cherry-picked

#205 Use the neo4j protocol as the default for tests as well.
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgs.java
  cypher-shell/src/main/java/org/neo4j/shell/log/AnsiLogger.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
Labels: 4.1
