Repository neo4j/cypher-shell, pull requests merged in 2020-04, with the labels that each got.

#214 Fix bug when running non-interactively and password change required
  cypher-shell/src/main/java/org/neo4j/shell/Main.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/util/Versions.java
Labels: 4.0, bug

#215 Fix bug when running non-interactively and password change required
  cypher-shell/src/main/java/org/neo4j/shell/Main.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/util/Versions.java
Labels: 4.1, bug, cherry-picked

#216 Support +ssc and +s protocols
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellMultiDatabaseIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellProtocolIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/ConnectionConfig.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgs.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/Encryption.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/ConnectionConfigTest.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
  cypher-shell/src/test/java/org/neo4j/shell/MainTest.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
  cypher-shell/src/test/java/org/neo4j/shell/state/BoltStateHandlerTest.java
Labels: 4.0, changelog

#218 Support +ssc and +s protocols
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellMultiDatabaseIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellProtocolIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/ConnectionConfig.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgHelper.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/CliArgs.java
  cypher-shell/src/main/java/org/neo4j/shell/cli/Encryption.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/ConnectionConfigTest.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
  cypher-shell/src/test/java/org/neo4j/shell/MainTest.java
  cypher-shell/src/test/java/org/neo4j/shell/cli/CliArgHelperTest.java
  cypher-shell/src/test/java/org/neo4j/shell/state/BoltStateHandlerTest.java
Labels: 4.1, changelog, cherry-picked
