Repository neo4j/cypher-shell, pull requests merged in 2020-07, with the labels that each got.

#232 Align cypher-shell PROFILE headers with embedded.
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TablePlanFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TableOutputFormatterTest.java
Labels: 4.2

#231 Handle errors while in TX gracefully.
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellTransactionIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/TransactionHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/state/ErrorWhileInTransactionException.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 4.1, bug, changelog

#234 Adjust test expectation for new parser error message
  cypher-shell/src/integration-test/java/org/neo4j/shell/MainIntegrationTest.java
Labels: 4.2

#233 4.2 tx handle error
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellTransactionIntegrationTest.java
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/CypherShell.java
  cypher-shell/src/main/java/org/neo4j/shell/TransactionHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/main/java/org/neo4j/shell/state/ErrorWhileInTransactionException.java
  cypher-shell/src/test/java/org/neo4j/shell/CypherShellTest.java
Labels: 4.2, cherry-picked
