Repository neo4j/cypher-shell, pull requests merged in 2020-05, with the labels that each got.

#219 Render Details column in plan table
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TablePlanFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TablePlanFormatterTest.java
Labels: 4.0

#221 4.1 render details column
  cypher-shell/src/integration-test/java/org/neo4j/shell/commands/CypherShellVerboseIntegrationTest.java
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TablePlanFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TablePlanFormatterTest.java
Labels: 4.1, cherry-picked

#222 Add support for multiline details column
  cypher-shell/src/main/java/org/neo4j/shell/prettyprint/TablePlanFormatter.java
  cypher-shell/src/test/java/org/neo4j/shell/prettyprint/TablePlanFormatterTest.java
Labels: 4.1
