Repository neo4j/cypher-shell, pull requests merged in 2020-01, with the labels that each got.

#195 Use db.indexes instead of showCurrentUser as ping
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.0, bug, changelog

#196 Use db.indexes instead of showCurrentUser as ping
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.1, bug, changelog, cherry-picked

#193 4.0 remove some transitive dependecies
  build.gradle
  cypher-shell/build.gradle
Labels: 4.0

#194 1.1 remove some transitive dependecies
  build.gradle
  cypher-shell/build.gradle
Labels: 1.1

#192 Remove some transitive dependencies
  build.gradle
  cypher-shell/build.gradle
Labels: 4.1
