Repository neo4j/cypher-shell, pull requests merged in 2020-03, with the labels that each got.

#211 Use java driver 4.0.1
  build.gradle
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.0

#212 Use java driver 4.0.1
  build.gradle
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
Labels: 4.1, cherry-picked

#210 Use db.ping when possible
  cypher-shell/src/main/java/org/neo4j/shell/state/BoltStateHandler.java
  cypher-shell/src/test/java/org/neo4j/shell/state/BoltStateHandlerTest.java
  cypher-shell/src/test/java/org/neo4j/shell/test/bolt/FakeResult.java
Labels: 4.1
